# 初学者向けPandas100本ノックver1.0.7
##### Shift + Enter で各セルのコードが実行されます
・print(ans[ 問題番号 ]) で回答コード例を表示  
・Python3エンジニア認定データ分析試験にも沿った問題内容   
・Pandasの各メソッドの説明は以下のサイトが分かりやすいです  
 　[note.nkmk.me](https://note.nkmk.me/pandas/)  
・"Data for Titanic passengers" from [VANDERBILT UNIVERSITY](https://biostat.app.vumc.org/wiki/Main/DataSets)  
  
**本コンテンツ作成時のpandasのバージョンは1.1.0**
  
作成日:2020年9月24日  
最終更新日:2023年1月16日  
再配布・改編不可  
作成者：[kunishou](https://qiita.com/kunishou)

In [5]:
# Shift + Enterで題材データ、回答コードを読み込んで下さい

import pandas as pd
import glob

#題材データをdfに読み込み(タイタニック号の乗客データ、テストの点数データ 等)
def initialize1():
    df = pd.read_csv('../input/titanic3.csv')
    return df

def initialize2():
    df = pd.read_csv('../input/data1.csv')
    return df

df = initialize1()
df2 = initialize2()
df3 = pd.read_csv('../input/data1_2.csv')
df4 = pd.read_csv('../input/data1_3.csv')
df5 = pd.read_csv('../input/data2.csv',encoding='cp932')

#回答コードをansリストに格納
path = sorted(glob.glob('../input/a_' + '*.txt'))

ans = []

for _ in range(len(path)):
    with open(path[_], 'r',encoding='utf-8') as f:
        ans.append(f.read())
        
print(ans[0])

[answer0]

このように回答コード例がここに表示されます。
各問題の回答コード例を表示するときはprintの前の
#を消して実行して下さい。

コード例をセル内にコピー&ペーストし
実行すると、正解のデータが表示されます

# Pandas基礎 (1 - 13)

In [6]:
# 【1】
# dfに読み込んだデータの最初の5行を表示
print(ans[1]) #回答表示

df = initialize1() #初期化

df.head()

[answer1]

df.head()


[tips]
.head()はデフォルトで先頭5行表示
()に表示したい行数を入れる
先頭10行表示は .head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [7]:
# 【2】
# dfに読み込んだデータの最後の5行を表示
print(ans[2]) #回答表示
df = initialize1() #初期化

df.tail()

[answer2]

df.tail()


[tips]
.tail()はデフォルトで最後の5行表示
()に表示したい行数を入れる
最後10行表示は .tail(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [8]:
# 【3】
# dfのDataFrameサイズを確認
print(ans[3]) #回答表示
df = initialize1() #初期化

df.shape

[answer3]

df.shape

(1309, 14)

In [9]:
# 【4】
# inputフォルダ内のdata1.csvファイルを
# 読み込みdf2に格納して、最初の5行を表示
print(ans[4]) #回答表示

df2 = pd.read_csv('../input/data1.csv')
df2.head()

[answer4]

df2 = pd.read_csv('../input/data1.csv')
df2.head()


[Tips]
・csvの読み込みはread_csv
・必要に応じてencoding=''を指定する
utf-8
shift_jis (日本語)
cp932 (Windows拡張文字含む日本語)

ex)
df2 = pd.read_csv('../input/data1.csv',encoding='utf-8')

  name  class  English  Mathematics  History
0    A      1       80           55       65
1    B      1       55          100       83
2    C      2       65           70       95
3    D      1       40           63       70
4    E      2       76           82       79

In [10]:
# 【5】
# dfのfareの列で昇順に並び替えて表示
print(ans[5]) #回答表示
df = initialize1() #初期化

df.sort_values('fare')

[answer5]

df.sort_values('fare')


[Tips]
・要素でソートするときはsort_valuesを使用
・デフォルトでは昇順
・降順でソートしたい場合は ascending=False を指定
・ソートする列を複数指定可能

ex)
降順でソート
df.sort_values('fare', ascending=False)

複数列でのソート
df.sort_values(['fare','age'])

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
363,2,0,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S,NaN,NaN,Belfast
223,1,0,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S,NaN,NaN,Belfast
170,1,1,"Ismay, Mr. Joseph Bruce",male,49.0,0,0,112058,0.0000,B52 B54 B56,S,C,NaN,Liverpool
1254,3,1,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,NaN,S,15,NaN,NaN
896,3,0,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0000,NaN,S,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,3,NaN,NaN
50,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Germantown, Philadelphia, PA"
49,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Austria-Hungary / Germantown, Philadelphia, PA"
183,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,3,NaN,NaN
1225,3,0,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S,NaN,261.0,NaN

In [11]:
# 【6】
# df_copyにdfをコピーして、最初の5行を表示
print(ans[6]) #回答表示
df = initialize1() #初期化

df_copy = df.copy()
df_copy.head()

[answer6]

df_copy = df.copy()
df_copy.head()


[Tips]
① df_copy = df と ② df_copy = df.copy() では
挙動が異なるので注意が必要。

①の場合、df_copyはdfを参照しているだけのため、
df側の値を変えると、df_copy側の値も変わる
(dfとdf_copyは連動)。

df側の値の変更をdf_copy側に反映させたくない
場合には②のcopy()を使う(dfとdf_copyは独立)。

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [22]:
# 【7】
# ① dfの各列のデータ型を確認
# ② dfのcabinの列のデータ型を確認
print(ans[7]) #回答表示
df = initialize1() #初期化

print(df.dtypes)
print(df['cabin'].dtype)

[answer7]

print(df.dtypes)
print(df['cabin'].dtype)


[Tips]
・DataFrameのすべての列のデータ型を確認したい場合は dtypes
・DataFrameの一つの列のデータ型を確認したい場合は dtype

※複数のコードの結果を表示したい場合、printを使用
(printをつけない場合、1行目のdtypesの結果しか表示されない)
pclass         int64
survived       int64
name             str
sex              str
age          float64
sibsp          int64
parch          int64
ticket           str
fare         float64
cabin            str
embarked         str
boat             str
body         float64
home.dest        str
dtype: object
str

In [13]:
# 【8】
# ① dfのpclassの列のデータ型をdtypeで確認
# ② 数値型から文字型に変換し、データ型をdtypeで確認
print(ans[8]) #回答表示
df = initialize1() #初期化

print(df['pclass'].dtype)
df['pclass'] = df['pclass'].astype(str)
print(df['pclass'].dtype)

[answer8]

print(df['pclass'].dtype)
df['pclass'] = df['pclass'].astype(str)
print(df['pclass'].dtype)


[Tips]
・データ型を変更する場合は astype を使用
・問題40の列同士の結合では、数値列と文字列を
結合しますが、データ型が異なると結合が上手く
いきません。両方の列のデータ型が同じになるように
astypeを使用してデータ型の変換をします。
int64
str

In [15]:
# 【9】
# dfのレコード数(行数)を確認
print(ans[9]) #回答表示
df = initialize1() #初期化

len(df)

[answer9]

len(df)


[Tips]
dataframeのレコード数(行数)を知りたい時は
len()を使用

1309

In [17]:
# 【10】
# dfのレコード数(行数)、各列のデータ型、欠損値の有無を確認
print(ans[10]) #回答表示
df = initialize1() #初期化

df.info()

[answer10]

df.info()


[Tips]
・レコード数(行数)、各列のデータ型、欠損値の有無の
　確認にはinfo()を使用
・RangeIndexがレコード数
・Data columnsがカラム数
・Non-Null Countがレコードが入ってる数
・今回、1309レコードだがcabinのNon-Null Countは
　295なので1309-295のレコードについては欠損している
<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   str
 11  boat       486 non-null    str
 12  body       121 non-null    float64
 13  home.dest  745 non-null    str
dtypes: float64(3), int64(4), str(7)
memory usage: 143.3 KB

In [19]:
# 【11】
# dfのsex,cabinの列の要素を確認
print(ans[11]) #回答表示
df = initialize1() #初期化

print(df['sex'].unique())
print(df['cabin'].unique())

[answer11]

print(df['sex'].unique())
print(df['cabin'].unique())


[Tips]
列に含まれる要素の確認にはunique()を使用
<StringArray>
['female', 'male']
Length: 2, dtype: str
<StringArray>
[     'B5', 'C22 C26',     'E12',      'D7',     'A36',    'C101',       nan,
 'C62 C64',     'B35',     'A23',
 ...
       'F',   'F G63',   'F E57',   'F E46',   'F G73',    'E121',   'F E69',
     'E10',      'G6',     'F38']
Length: 187, dtype: str

In [21]:
# 【12】
# dfの列名一覧をlist形式で表示
print(ans[12]) #回答表示
df = initialize1() #初期化

df.columns.tolist()

[answer12]

df.columns.tolist()


[Tips]
・列名を一覧表示するにはcolumnsを使用
・.tolist()を付けることでlist形式に変換
・ndarray形式で表示する場合は.valuesを使用

df.columns.values

['pclass',
 'survived',
 'name',
 'sex',
 'age',
 'sibsp',
 'parch',
 'ticket',
 'fare',
 'cabin',
 'embarked',
 'boat',
 'body',
 'home.dest']

In [23]:
# 【13】
# dfのインデックス一覧をndaaray形式で表示
print(ans[13]) #回答表示
df = initialize1() #初期化#

df.index.values

[answer13]

df.index.values


[Tips]
・インデックスを一覧表示するには.indexを使用
・.valuesを付けることでndaaray形式に変換
・list形式で表示する場合はtolist()を使用

df.index.tolist()

array([   0,    1,    2, ..., 1306, 1307, 1308], shape=(1309,))

# データ抽出 (14 - 32)

In [ ]:
# 【14】
# dfのnameの列のみ表示
#print(ans[14]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【15】
# dfのnameとsexの列のみ表示
#print(ans[15]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【16】
# dfのindex(行)の4行目までを表示
#print(ans[16]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【17】
# dfのindex(行)の4行目から10行目までを表示
#print(ans[17]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【18】
# locを使ってdf全体を表示
#print(ans[18]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【19】
# locを使ってdfのfare列をすべて表示
#print(ans[19]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【20】
# locを使ってdfのfare列の10のラベルまで表示
#print(ans[20]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【21】
# locを使ってdfのnameとticketの列をすべて表示
#print(ans[21]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【22】
# locを使ってdfのnameからcabinまでの列をすべて表示
#print(ans[22]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【23】
# ilocを使ってdfのage列を5行目まで表示
#print(ans[23]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【24】
# dfのname,age,sexの列のみ抽出しdf_copyに格納
# その後outputフォルダにcsvファイルで出力
# 出力ファイル名はsample.csv
#print(ans[24]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【25】
# dfのage列の値が30以上のデータのみ抽出
#print(ans[25]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【26】
# dfのsex列がfemaleのデータのみ抽出
#print(ans[26]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【27】
# dfのsex列がfemaleでかつageが40以上のデータのみ抽出
#print(ans[27]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【28】
# queryを用いてdfのsex列がfemaleでかつageが40以上のデータのみ抽出
#print(ans[28]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【29】
# dfのname列に文字列「Mrs」が含まれるデータを表示
#print(ans[29]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【30】
# dfの中で文字列型の列のみを表示
#print(ans[30]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【31】
# dfの各列の要素数の確認
#print(ans[31]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【32】
# dfのembarked列の要素と出現回数の確認
#print(ans[32]) #回答表示
df = initialize1() #初期化

# データ加工 (33 - 58)

In [ ]:
# 【33】
# dfのindex名が「3」のage列を
# 30から40に変更し、先頭の5行を表示
#print(ans[33]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【34】
# dfのsex列にてmale→0、femlae→1に
# 変更し、先頭の5行を表示
#print(ans[34]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【35】
# dfのfare列に100を足して、
# 先頭の5行を表示
#print(ans[35]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【36】
# dfのfare列に2を掛けて、
# 先頭の5行を表示
#print(ans[36]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【37】
# dfのfare列を小数点以下で丸めて、先頭の5行を表示
#print(ans[37]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【38】
# dfに列名「test」で値がすべて1の
# カラムを追加し、先頭の5行を表示
#print(ans[38]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【39】
# dfにcabinとembarkedの列を「_」で
# 結合した列を追加(列名は「test」)し、
# 先頭の5行を表示
#print(ans[39]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【40】
# dfにageとembarkedの列を「_」で
# 結合した列を追加(列名は「test」)し、
# 先頭の5行を表示
#print(ans[40]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【41】
# dfからbodyの列を削除し、最初の5行を表示
#print(ans[41]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【42】
# dfからインデックス名「3」の行を削除し、最初の5行を表示
#print(ans[42]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【43】
# df2の列名を'name', 'class', 'Biology', 'Physics', 'Chemistry'に変更
# df2の最初の5行を表示
#print(ans[43]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【44】
# df2の列名を'English'をBiology'に変更
# df2の最初の5行を表示
#print(ans[44]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【45】
# df2のインデックス名「1」を「10」に変更
# df2の最初の5行を表示
#print(ans[45]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【46】
# dfのすべての列の欠損値数を確認
#print(ans[46]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【47】
# dfのage列の欠損値に30を代入
# その後、ageの欠損値数を確認
#print(ans[47]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【48】
# dfでひとつでも欠損値がある行を削除
# その後、dfの欠損値数を確認
#print(ans[48]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【49】
# dfのsurvivedの列をndarray形式(配列)で表示
#print(ans[49]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【50】
# dfの行をシャッフルして表示
#print(ans[50]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【51】
# dfの行をシャッフルし、インデックスを振り直して表示
#print(ans[51]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【52】
# ①df2の重複行数をカウント
# ②df2の重複行を削除し、df2を表示
#print(ans[52]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【53】
# dfのnameの列をすべて大文字に変換し表示
#print(ans[53]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【54】
# dfのnameの列をすべて小文字に変換し表示
#print(ans[54]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【55】
# dfのsex列に含まれる「female」という単語を
# 「Python」に置換。その後、1行目の
# 「female」が「Python」に置き換わったことを確認
#print(ans[55]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【56】
# dfのname列1行目の「Allen, Miss. Elisabeth Walton」の
# 「Elisabeth」を消去(import reをインポート)
#print(ans[56]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【57】
# df5の都道府県列と市区町村列を空白がないように
# 「_」で結合(新規列名は「test2」)し、先頭5行を表示
# ※df5の「test」列は通常通り結合した場合の結果
#print(ans[57]) #回答表示

In [ ]:
# 【58】
# df2の行と列を入れ替えて表示
#print(ans[58]) #回答表示
df2 = initialize2() #初期化

# マージと連結(59 - 65)

In [ ]:
# 【59】
# df2にdf3を左結合（結合キーはname）し、df2に格納
#print(ans[59]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【60】
# df2にdf3を右結合（結合キーはname）し、df2に格納
#print(ans[60]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【61】
# df2にdf3を内部結合（結合キーはname）し、df2に格納
#print(ans[61]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【62】
# df2にdf3を外部結合し、df2に格納
#print(ans[62]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【63】
# df2とdf4を列方向に連結し、df2に格納
#print(ans[63]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【64】
# df2とdf4を列方向に連結後、重複している
# name列の片方を削除し、df2に格納
#print(ans[64]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【65】
# df2とdf4を行方向に連結し、df2に格納
#print(ans[65]) #回答表示
df2 = initialize2() #初期化

# 統計 (66 - 79)

In [ ]:
# 【66】
# dfのage列の平均値を確認
#print(ans[66]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【67】
# dfのage列の中央値を確認
#print(ans[67]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【68】
# ①df2の生徒ごとの合計点（行方向の合計）
# ②df2の科目ごとの点数の総和（列方向の合計）
#print(ans[68]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【69】
# df2のEnglishで得点の最大値
#print(ans[69]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【70】
# df2のEnglishで得点の最小値
#print(ans[70]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【71】
# df2においてclassでグルーピングし、クラスごとの科目の
# 最大値、最小値、平均値を求める(name列は削除しておく)
#print(ans[71]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【72】
# dfの基本統計量を確認(describe)
#print(ans[72]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【73】
# dfの各列間の(Pearson)相関係数を確認
#print(ans[73]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【74】
# scikit-learnを用いてdf2のEnglish、Mathematics、History列を標準化する
# (from sklearn.preprocessing import StandardScalerをインポート)
#print(ans[74]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【75】
# scikit-learnを用いてdf2のEnglish列を標準化する
# (from sklearn.preprocessing import StandardScalerをインポート)
#print(ans[75]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【76】
# scikit-learnを用いてdf2のEnglish、Mathematics、History列を
# Min-Maxスケーリングする
# (from sklearn.preprocessing import MinMaxScalerをインポート)
#print(ans[76]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【77】
# dfのfare列の最大値、最小値の行名を取得
#print(ans[77]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【78】
# dfのfare列の0、25、50、75、100パーセンタイルを取得
#print(ans[78]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【79】
# ①dfのage列の最頻値を取得
# ②value_counts()にてage列の要素数を
# 確認し、①の結果の妥当性を確認
#print(ans[79]) #回答表示
df = initialize1() #初期化

# ラベリング (80 - 81)

In [ ]:
# 【80】
# dfのsex列をラベルエンコーディングし、
# dfの先頭5行を表示
# (from sklearn.preprocessing import LabelEncoderをインポート)
#print(ans[80]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【81】
# dfのsex列をOne-hotエンコーディングし、
# dfの先頭5行を表示
#print(ans[81]) #回答表示
df = initialize1() #初期化

# Pandasプロット (82 - 89)
Pandasプロットの機能については以下のサイトの説明が分かりやすいです  
[自調自考の旅](https://own-search-and-study.xyz/2016/08/03/pandas%E3%81%AEplot%E3%81%AE%E5%85%A8%E5%BC%95%E6%95%B0%E3%82%92%E4%BD%BF%E3%81%84%E3%81%93%E3%81%AA%E3%81%99/)

In [ ]:
# 【82】
# dfのすべての数値列のヒストグラムを表示
#print(ans[82]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【83】
# dfのage列をヒストグラムで表示
#print(ans[83]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【84】
# df2のname列の要素ごとの3科目合計得点を棒グラフで表示
#print(ans[84]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【85】
# df2のname列の要素ごとの3科目を棒グラフで
# 並べて表示
#print(ans[85]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【86】
# df2のname列の要素ごとの3科目を積み上げ棒グラフで表示
#print(ans[86]) #回答表示
df2 = initialize2() #初期化

In [ ]:
# 【87】
# dfの各列間の散布図を表示
# (from pandas.plotting import scatter_matrixをインポート)
#print(ans[87]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【88】
# dfのage列とfare列で散布図を作成
#print(ans[88]) #回答表示
df = initialize1() #初期化

In [ ]:
# 【89】
# 【88】で描画したグラフに「age-fare scatter」という
# グラフタイトルをつける
#print(ans[89]) #回答表示
df = initialize1() #初期化

# タイタニック号の生存者予測 (90 - 100)  
これまで触れてきたタイタニック号の乗客データを使用して、乗客の生存有無を  
予測してみます。  
  
※90～100については順番通りにやらないと上手く動作しません

In [ ]:
# 【90】ラベルエンコーディング
# df_copyのsexとembarked列をラベルエンコーディング
# (from sklearn.preprocessing import LabelEncoderをインポート)
# (df_copyはdfをコピーしたもの)
#print(ans[90]) #回答表示
df_copy =df.copy()

In [ ]:
# 【91】欠損値確認
# df_copyの欠損値を確認
#print(ans[91]) #回答表示

In [ ]:
# 【92】欠損値補完
# df_copyのage、fare列の欠損値を各列の平均値で補完
#print(ans[92]) #回答表示

In [ ]:
# 【93】不要列の削除
# df_copyの中で機械学習で使用しない不要な行を削除
# (name, ticket, cabin, boat, body, home.destを削除)
#print(ans[93]) #回答表示

In [ ]:
# 【94】ndarray形式への変換
# ①df_copyのpclass、age、sex、fare、embarkedの列を抽出し、ndarray形式に変換
# ②df_copyのsurvivedの列を抽出し、ndarray形式に変換
# (①をfeatures、②をtargetという変数にそれぞれ格納)
#print(ans[94]) #回答表示

In [ ]:
# 【95】学習データとテストデータに分割
# 【94】で作成したfeatrues、targetを学習データとテストデータに分割
# (from sklearn.model_selection import  train_test_splitをインポート)
# ※分割時のパラメータは次を指定 test_size=0.3 random_state=0
#print(ans[95]) #回答表示

In [ ]:
# 【96】学習の実行
# 学習データ(features、target)を用いランダムフォレストにて学習を実行
# (from sklearn.ensemble import RandomForestClassifierをインポート)
# ※パラメータは次を指定 n_estimators=100 random_state=0
#print(ans[96]) #回答表示

In [ ]:
# 【97】予測の実行
# test_Xデータの乗客の生存を予測
#print(ans[97]) #回答表示

In [ ]:
# 【98】予測精度の確認
# 予測結果がtest_y(生存有無の答え)とどれぐらい
# 整合していたかを確認(評価指標はaccuracy)
# (from sklearn.metrics import accuracy_scoreをインポート)
#print(ans[98]) #回答表示

In [ ]:
# 【99】重要度の確認
# 学習における各列(特徴量)の
# 重要度を表示
#print(ans[99]) #回答表示

In [ ]:
# 【100】予測結果のcsv出力
# test_Xの予測結果をcsvでoutputフォルダに出力(ファイル名は「submission.csv」)
# (headerは不要)
#print(ans[100]) #回答表示

# ノックお疲れ様でした
各セルのoutput表示をすべてクリアにしたい場合は、ツールバーの  
「Kernel」→「Restart & Clear Output」を実行して下さい。